version: '3.2'
services:

  #PHP Service
  backend-app:
    image: wtube_backend:latest
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: http://localhost
    working_dir: /var/www
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    expose:
      - "80"
    networks:
      - wtube-network

  #Nginx Service
  server-app:
    image: wtube_server:latest
    restart: unless-stopped
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "10001:80"
    networks:
      - wtube-network

#Docker Networks
networks:
  wtube-network:
    driver: overlay
    attachable: true
